### ISSUE TITLE
Luis Hello !!!

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keysubtracter#15]
Luis, can you implement this algorithm to keyubstractor ?

https://bitcointalk.org/index.php?topic=5244940.msg57326261#msg57326261

Regards.

**Comment by albertobsd** [comment]
Well that petition is very similar to the 

https://github.com/albertobsd/keysubtracter/issues/5 Issue.

And yes it can be made, but in another program.

however Publickey Division is some tricky because if the division is not an Exact number the result may land in another key space even in a upper key space, just to say some example: if we divide the publickey of the number 11 between 2 the result may land in the bit 250 or 256 or 180, just to say something, i don't have idea where it can landing.

And just to add some extra difficult to this, we usually work with unknow publickeys, we are blind to know the result of the division.

Please use the https://github.com/albertobsd/keysubtracter/issues/5 Issue. To post any other comment about this topic.

Regards!
